server:
  port: 8081
spring:
  application:
    name: identity-service
  config:
    import: "optional:configserver:http://localhost:8888"
  datasource:
    url: jdbc:h2:mem:identitydb;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password: ""
  jpa:
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
  h2:
    console:
      enabled: true

# fallback nếu config-server chưa chạy (config-server sẽ ghi đè khi có mặt)
jwt:
  secret: "rikkeibank-super-secret-key-please-change-0123456789"
  access-ttl-minutes: 15
  refresh-ttl-days: 30

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
