# Cấu hình DÙNG CHUNG cho mọi microservice (Spring Cloud Config, native)
jwt:
  secret: "rikkeibank-super-secret-key-please-change-0123456789"
  access-ttl-minutes: 15
  refresh-ttl-days: 30

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,circuitbreakers,circuitbreakerevents
